### ISSUE TITLE
请问想要分割新类别的物体应该怎么做呢

### ISSUE THREAD

**Issue by aprilliuwei** [PRBonn/rangenet_lib#39]

**Comment by Chen-Xieyuanli** [comment]
Hey @aprilliuwei, 感谢给我们留言！我们目前正在进行一项开放世界集算法研究(检测训练集中没有的物体)，目前论文正在盲审过程中，如被录用，我们会第一时间放在主页，欢迎关注我们主页与我们保持联系。由于这个问题与rangenet_lib无关，并与https://github.com/PRBonn/LiDAR-MOS/issues/6重复，我将关闭这个问题。

Q: How to segment the objects those are not in the KITTI training data?
A: We just submitted a work to detect and segment objects in an open-world set. The submission is still under double-blind reviewing and we will release the paper after the review on our website.
Since it is duplicated with [issue 6](https://github.com/PRBonn/LiDAR-MOS/issues/6), I will close this one.
